# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54043b1978eea4adce0a0abcb646bab091d3ca44133cccca17328ecb7d7ee4ab07dfbf5fb90bfae2ded748ca2a098245a96e391f965e588aa1710db06d95ad49

test:
  secret_key_base: 5439b2a48006d9c5cd521442d99df3d3845d7bcc0bc93fc3dacd8f852974745adc682814e1634f5fc9ddc8360ebd57f33ad65b2c2a0a60bd9b6f8d5ec74fb010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
